### ISSUE TITLE
dynamic validation

### ISSUE THREAD

**Issue by jHodgkinson** [JaroslawWaliszko/ExpressiveAnnotations#43]
I have a model that is generated X number of times. I basically want to require validation on a textbox field (CountyCollection_0__PatentRegistrationNumber) if  a hidden field's value = true (this is toggled true/false if a specific checkboxlist item is checked). 

Many thanks in advance as always!

model:

        [Display(Name = "Patent Registration Value")]
        public String PatentRegistrationValue { get; set; }

        [AssertThat("IsPatentRegNumberRequired()", ErrorMessage = "Patent Registration Number is required")]
        [Display(Name = "Patent Registration Number")]
        public String PatentRegistrationNumber { get; set; }

view:

If you checked Patent Law, what is the Registration #:
&lt;input class="patent-item" id="patentItem" name="patentItem" type="hidden" value="0" /&gt;
&lt;input id="CountyCollection_0__PatentRegistrationValue" name="CountyCollection[0].PatentRegistrationValue" type="hidden" value="false" /&gt;

&lt;input data-val="true" data-val-assertthat="Patent Registration Number is required" data-val-assertthat-constsmap="{}" data-val-assertthat-expression="&quot;IsPatentRegNumberRequired()&quot;" data-val-assertthat-fieldsmap="{&quot;PatentRegistrationValue&quot;:&quot;string&quot;}" id="CountyCollection_0__PatentRegistrationNumber" name="CountyCollection[0].PatentRegistrationNumber" type="text" value="" /&gt;
&lt;span class="field-validation-valid" data-valmsg-for="CountyCollection[0].PatentRegistrationNumber" data-valmsg-replace="true"&gt;&lt;/span&gt;

client script:

//expressive annotations custom client function
ea.addMethod('IsPatentRegNumberRequired', function () {

    //local declare
    var bStatus = false;

    //get current item
    var currentItem = $(this).parents("div").find(".patent-item");

    //get patent reg value textbox
    var patentBox = $('#CountyCollection_' + currentItem.val() + '__PatentRegistrationValue');

    //check value
    if (patentBox.val() == "true")
    {
        //set if true
        bStatus = true;
    }

    //return status
    return bStatus;
});

**Comment by jHodgkinson** [comment]
Jaroslaw - many thanks. will give this a try. I apologize for the delay... was out on holiday...

**Comment by jHodgkinson** [comment]
Jaroslow - I have multiple dropdownlists and need to make sure the user provided at least one value from all the lists. the values are currently stored in an IEnumerable<String>  is this possible? I was thinking something like below... Many thanks!

        [Display(Name = "Specialty Areas"), RequiredIf("!ListHasValues(SpecialtyCollection_BusinessLaw) && !ListHasValues(SpecialtyCollection_CriminalLaw) && !ListHasValues(SpecialtyCollection_EstatePlanning)", ErrorMessage = "You must select at least one specialty area per county")]        
        public String SpecialtyAreas { get; set; }

        [Display(Name = "Specialty Collection Business Law")]
        public IEnumerable<String> SpecialtyCollection_BusinessLaw { get; set; }

        [Display(Name = "Specialty Collection Business Law List")]
        public IEnumerable<SelectListItem> SpecialtyCollection_BusinessLawList { get; set; }

        [Display(Name = "Specialty Collection Criminal Law")]
        public IEnumerable<String> SpecialtyCollection_CriminalLaw { get; set; }

        [Display(Name = "Specialty Collection Criminal Law List")]
        public IEnumerable<SelectListItem> SpecialtyCollection_CriminalLawList { get; set; }

        [Display(Name = "Specialty Collection Estate Planning")]
        public IEnumerable<String> SpecialtyCollection_EstatePlanning { get; set; }

        [Display(Name = "Specialty Collection Estate Planning List")]
        public IEnumerable<SelectListItem> SpecialtyCollection_EstatePlanningList { get; set; }

        public bool ListHasValues(IEnumerable<String> oList)
        {
            return oList.Count() > 0 ? true : false;
        }

**Comment by JaroslawWaliszko** [comment]
Is there any issue with that code?

**Comment by jHodgkinson** [comment]
Jaroslow - below is there error info I am seeing:

Error loading Partial View (file: ~/Views/MacroPartials/Apps LRS Join Renew.cshtml). Exception: System.Web.HttpException (0x80004005): Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Problem related to RequiredIfAttribute attribute for SpecialtyAreas field with following expression specified: !ListHasValues(SpecialtyCollection_AdministrativeLaw) ---> System.InvalidOperationException: Parsing failed. Invalid expression: !ListHasValues(SpecialtyCollection_AdministrativeLaw) ---> System.InvalidOperationException: Invalid token started at: _AdministrativeLaw)

**Comment by JaroslawWaliszko** [comment]
I think you have outdated version of the library. Which version is registered in the packages.config file?

**Comment by jHodgkinson** [comment]
I don't see it listed so I must have not installed using NuGet (manual install). should I use NuGet and install into my project?

**Comment by JaroslawWaliszko** [comment]
Sure, it is the most convenient way - https://github.com/JaroslawWaliszko/ExpressiveAnnotations#installation

**Comment by JaroslawWaliszko** [comment]
Your current product version has to be 2.2.0 or below I think, because underscore support was added in 2.2.1: https://github.com/JaroslawWaliszko/ExpressiveAnnotations/releases

The complete package is what you're looking for (current version is 2.4.1): `PM> Install-Package ExpressiveAnnotations`

**Comment by jHodgkinson** [comment]
PM> Install-Package ExpressiveAnnotations
Attempting to resolve dependency 'Newtonsoft.Json (≥ 4.5.11)'.
Attempting to resolve dependency 'jQuery (≥ 1.8.2)'.
Attempting to resolve dependency 'jQuery.Validation (≥ 1.10.0)'.
Attempting to resolve dependency 'Microsoft.jQuery.Unobtrusive.Validation (≥ 3.1.1)'.
'ExpressiveAnnotations 2.4.1' already installed.
ncba.MVC already has a reference to 'ExpressiveAnnotations 2.4.1'.

**Comment by jHodgkinson** [comment]
I physically removed the files (from previous manual install) and then installed the package and the files updated... going through now trying to get the validation to work... will keep you posted. thx!

**Comment by JaroslawWaliszko** [comment]
Good, maybe there was some kind of a conflict or double-install attempt. Nevertheless 2.4.1 package contains following files which should be referenced:
* expressive.annotations.validate.js - v2.4.0,
* ExpressiveAnnotations.dll - v2.2.8,
* ExpressiveAnnotations.MvcUnobtrusiveValidatorProvider.dll - v2.2.5

What's more, your method:
```
public bool ListHasValues(IEnumerable<String> oList)
{
    return oList.Count() > 0 ? true : false;
}
```
looks better if written in the following manner:
```
public bool ListHasValues(IEnumerable<String> oList)
{
    return oList != null && oList.Any();
}
```
At the client side `SpecialtyCollection_AdministrativeLaw` should be rendered as field with JSON-serialized value, to be then automatically extracted, deserialized and provided to the custom method, e.g.
```
@Html.Hidden("SpecialtyCollection_AdministrativeLaw", 
    JsonConvert.SerializeObject(Model.SpecialtyCollection_AdministrativeLaw))

ea.addMethod("ListHasValues", function (list) {
    return list.length > 0; // list is properly JSON-deserialized array
});
```

Of course, instead of manual way, better is to provide templates for arrays of various types, e.g.
```
@using Newtonsoft.Json
@model string[]
@Html.Hidden("", JsonConvert.SerializeObject(Model))
```
and then (you gain out of the box compilation level checking for model properties naming changes):
```
@Html.EditorFor(model => model.SpecialtyCollection_AdministrativeLaw, "StringArray") 
```

More context and/or alternative approaches you should get from here: https://github.com/JaroslawWaliszko/ExpressiveAnnotations/issues/38
