### ISSUE TITLE
Is it Possible To Reference a Sibling Classes Properties?

### ISSUE THREAD

**Issue by hatfies3** [JaroslawWaliszko/ExpressiveAnnotations#49]
Sorry if this is already covered elsewhere. 

Is it only possible to reference properties of the current class, or is it possible to reference properties from a sibling class in a slightly more complex class structure?

i.e. Is it possible for a RequiredIf expression on ChildClass1's Property A to reference ChildClass2's Property A?  Example below fails.

    public class RootClass
    {
        public virtual ChildClass1 One { get; set; }
        public virtual ChildClass2 Two { get; set; }
    }

    public class ChildClass1 
    {
        [RequiredIf(@"Two.A == 'SomeValue'")]
        public string A { get; set; }      
    }

    public class ChildClass2 
    {

        public string A { get; set; }
      
    }

**Comment by JaroslawWaliszko** [comment]
Hi, this usage is not correct. You have no access to property `Two` in the context of `ChildClass1` because it does not exists. The exception you have most likely seen says it:
```
Parse error on line 1, column 1:
... Two.A == 'SomeValue' ...
    ^--- Only public properties, constants and enums are accepted. Identifier 'Two.A' not known.
```
