### ISSUE TITLE
Combining AssertThat and RequiredIf

### ISSUE THREAD

**Issue by ateetv** [JaroslawWaliszko/ExpressiveAnnotations#50]
Hi Jaroslaw,

I would like to know if it was possible to combine the two - "AssertThat" and "RequiredIf". This is the example of the business rule that I would like to code:

Model Class
FirstName
LastName
EnrollmentDate

Validation - The EnrollmentDate should be greater than today's date if the FirstName = "John" and LastName = "Doe". 

The first name and last name are not required fields.

**Comment by JaroslawWaliszko** [comment]
Hi, it is possible. You can combine multiple attributes if you wish. 
I don't know what have you tried, but the code is very simple and should look as follows:
```
public string FirstName { get; set; }
public string LastName { get; set; }

[RequiredIf("FirstName == 'John' && LastName == 'Doe'")]
[AssertThat("EnrollmentDate > Today()")]
public DateTime? EnrollmentDate { get; set; }
```
