### ISSUE TITLE
AssetThat Not Working

### ISSUE THREAD

**Issue by gdycus** [JaroslawWaliszko/ExpressiveAnnotations#53]
If IsNewOrder == true, Adults must be greater than 0. When IsNewOrder == false, Adults does not need to be greater than 0. But when IsNewOrder == false and Adults == 0, the following error is still displayed. Any suggestions? Thanks!

`[AssertThat("IsNewOrder == true && Adults > 0", ErrorMessage = "At least one adult is required")]`

**Comment by JaroslawWaliszko** [comment]
Logic behaves correctly, it's your condition which is broken and does not cover all cases.
Proper version is:

`[AssertThat("IsNewOrder && Adults > 0 || !IsNewOrder", ErrorMessage = "At least one ...")]`
