### ISSUE TITLE
Nuget 4.5 core dll not working.

### ISSUE THREAD

**Issue by 4imble** [JaroslawWaliszko/ExpressiveAnnotations#57]
I initially pulled in the full nuget package but realised i only needed the dll as I handle my own validation on the client.

When I removed that and than added the core package instead... it would not work. I had to remove the dll that it had referenced in the lib45 folder in favour of the one in the lib40 folder. 

This is in a .net 4.5 project.

**Comment by JaroslawWaliszko** [comment]
I'm currently in front of the phone and I'm not able to check that issue
anytime soon, but is there any error thrown or some other symptoms
indicating of what could possibly go wrong?

**Comment by 4imble** [comment]
Apologies i was away for the weekend. I'll have a go at reproducing it sometime today and give some more information.

**Comment by 4imble** [comment]
Unable to reproduce this now. Very Strange.

**Comment by JaroslawWaliszko** [comment]
Thanks, good it works ok. If you will notice any other potential problems, or will be able to reproduce this one anytime in the future, feel free to report an issue. Best regards.
