### ISSUE TITLE
jQuery undefined

### ISSUE THREAD

**Issue by lrrr-persei-8** [JaroslawWaliszko/ExpressiveAnnotations#58]
Hi there,
 I am new to MVC and was trying to use your expressive.annotations.validate library/scripts. I have tried but I cannot figure out a solution to the following problem:
'jQuery is not defined' and the file that is in error is expressive.annotations.validate.js, (Line 489). I have attached pictures to illustrate the same.
Any help will be greatly appreciated,
Thanks
Jason
![1](https://cloud.githubusercontent.com/assets/12143360/7358007/a404aaa6-ed00-11e4-885a-c90cacd281ff.png)
![2](https://cloud.githubusercontent.com/assets/12143360/7358006/a3da90e0-ed00-11e4-948e-4dd95e352f39.png)

**Comment by JaroslawWaliszko** [comment]
Hi, is **jQuery** library loaded on your page?
Expand *Scripts* node to check if it is there:

![image](https://cloud.githubusercontent.com/assets/1596462/7358077/7cccbc7a-ed33-11e4-8107-95b970f81d9f.png)
