### ISSUE TITLE
No more than 27 unique attributes of the same type can be applied for a single field or property

### ISSUE THREAD

**Issue by rwil02** [JaroslawWaliszko/ExpressiveAnnotations#59]
I understand WHY you've got this.
What I can't understand is why it's triggering for me.

I've got a POCO "order object" with a list of POCO "line objects"
Neither inherit from anything else.
For the line object I have a "RequiredIf" attribute on 11 of the 12 properties (property 12 is "ProductCode")
All saying "ProductCode != null"
8 of the 11 are string, but as I remove the attributes, the error is thrown on the next property to be rendered out, regardless of type

My List contains 2 line objects, one of which has a null product code

**Comment by rwil02** [comment]
Ah, got it.  I slipped on the intellisense and got @Html.Action instead of @Html.ActionLink and was getting a stack recursion.

See what happens as soon as you stop looking too hard :)

**Comment by JaroslawWaliszko** [comment]
Cool, good it works.
Regards
