### ISSUE TITLE
NuGet versioning failure (I'm guessing)

### ISSUE THREAD

**Issue by rwil02** [JaroslawWaliszko/ExpressiveAnnotations#60]
UI in Nuget says:
v 2.4.5
Dependencies
Newtonsoft.Json >= 4.5.11

My project has 6.0.8.18111 referenced

While it runs fine in Visual Studio, come deployment time it fails.
Adding in 
    <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.8.0" newVersion="6.0.8.18111" />
      </dependentAssembly>
to the web config doesn't work (just makes the error not tell you the assembly version) which makes me suspect there's another dependency further down as well.

**Comment by JaroslawWaliszko** [comment]
I was unable to reproduce this issue. Either the description provides insufficient repro steps or the problem has different origin, not related to EA.
