### ISSUE TITLE
ErrorMessage

### ISSUE THREAD

**Issue by gdycus** [JaroslawWaliszko/ExpressiveAnnotations#61]
Any suggestion on how to pull off the following? I need the message to include the min age.

[ExpressiveAnnotations.Attributes.AssertThat("Age < ChildMinAge", ErrorMessage = "You must be older than {ChildMinAge} to mountain bike")]

**Comment by JaroslawWaliszko** [comment]
If you want the actual value, EA doesn't provide an option to do that.

**Comment by JaroslawWaliszko** [comment]
I've decided to implement that idea. Initial commit pushed here: https://github.com/JaroslawWaliszko/ExpressiveAnnotations/commit/0184852a5eea99b7317b895a3f5df4ad1ed9b138. For sure needs to be yet refactored, optimized and unit-tested. If you have any suggestions, just give a hint here. Regards.

**Comment by JaroslawWaliszko** [comment]
done in [2.6.2](https://github.com/JaroslawWaliszko/ExpressiveAnnotations/releases/tag/v2.6.2)
