### ISSUE TITLE
Prevent RequiredIf firing validation

### ISSUE THREAD

**Issue by danbrentley** [JaroslawWaliszko/ExpressiveAnnotations#62]
Hi,

I've found issues similar to this, but none that seem to match my requirements exactly. I have a drop-down list (TypeId), and when a particular option is selected another text box (TypeOther) is made required.

    [Required]
    public int TypeId { get; set; }
    [RequiredIf("TypeId = 9")
    public string TypeOther { get; set; }

The RequiredIf unobtrusive js works perfectly well, if anything a bit too well. As soon as the user selects the option from the drop down list, the validation message appears immediately on the text box. As the text box is after the drop down selection, the user is being warned to fill in a field that they haven't got to yet.

Is it possible to change this behaviour so that when RequiredIf equates to true, it doesn't automatically try and validate the field? And instead waits for the user to perhaps exit the text box?

Cheers,
Dan

**Comment by JaroslawWaliszko** [comment]
Hi,

The short answer is that you can achieve it with the following setting:
```
<script>
    ea.settings.dependencyTriggers = undefined;
```
(do not forget to refresh your browser cache after this change)

See section regarding [frequency of dependent fields validation](https://github.com/JaroslawWaliszko/ExpressiveAnnotations#how-to-control-frequency-of-dependent-fields-validation) for a more complete explanation.

Regards
