### ISSUE TITLE
Unable to get property 'split' of undefined or null reference

### ISSUE THREAD

**Issue by rapidvelo** [JaroslawWaliszko/ExpressiveAnnotations#64]
Hi there,

I'm getting an error (Unable to get property 'split' of undefined or null reference) pointing to File: expressive.annotations.validate.js, Line: 437, Column: 17 ($.each(api.settings.dependencyTriggers.split(/\s+/), function(idx, event) )

I haven't touched the expressive.annotations.validate.js file and the dependency Triggers are unchanged to 'change paste keyup'.

**Comment by JaroslawWaliszko** [comment]
Hi,

can you reproduce it? What browser are you using?

**Comment by rapidvelo** [comment]
IE 11.   But in Chrome as well the client validation is not showing.    I removed your package in Visual Studio and re-added to see if that helped without any luck.

**Comment by JaroslawWaliszko** [comment]
And what about the mvc sample project? Is it working for you correctly?

**Comment by nunos7** [comment]
Hi, this same behaviour happened to me because i have this line of code:
```javascript
ea.settings.dependencyTriggers = undefined;
```

In previous versions my code was ok with this line... 

In documentation:

> Default value is 'change paste keyup' (for more information check eventType parameter of jQuery bind() method). If you want to turn this feature off entirely, set it to __undefined__ (validation will be fired on form submit attempt only).


NS

**Comment by rapidvelo** [comment]
Thanks NS - You were right -- I forgot I had this line duplicated on another JS section.    I did add this to solve another issue of showing the validation only when the submit button is pressed, as opposed to keyup or pasting it in.   When suppressing and holding the submit button the validation message is present, however after it doesn't let you submit the form the validation message disappears?   

Is there a way around this to keep displaying the error message?

Thank you

**Comment by nunos7** [comment]
Hi @rapidvelo, i put this line of code because i want to turn off this feature, but today i have the same issue with this line...
Today if i want to turn off this feature (dependencyTriggers) what can i do?
To test i put ea.settings.dependencyTriggers = undefined; but documentation say to set it to undefined...

NS

**Comment by rapidvelo** [comment]
Agreed @nunos7 .

@JaroslawWaliszko do you have an ideas for this scenario?   Thank you.

**Comment by JaroslawWaliszko** [comment]
Unfortunately I have only phone with me for the next few days. Probably the
simplest fix I can think of right now is, instead of `undefined` use empty
string to initialize triggers, i.e. `ea.settings.dependencyTriggers = '';`.
Give it a try.

Agreed @nunos7 <https://github.com/nunos7> .

@JaroslawWaliszko <https://github.com/JaroslawWaliszko> do you have an
ideas for this scenario? Thank you.

—
Reply to this email directly or view it on GitHub
<https://github.com/JaroslawWaliszko/ExpressiveAnnotations/issues/64#issuecomment-119981755>
.

**Comment by rapidvelo** [comment]
Unfortunately no luck.     I’m in no rush but would be great when you’re back if you can have a peek.

**Comment by JaroslawWaliszko** [comment]
Setting to empty string should work. Maybe your browser cache was preventing the change. Nevertheless thanks for posting that issue, fix is pushed here: https://github.com/JaroslawWaliszko/ExpressiveAnnotations/commit/fb9ec6a620ee49aadafe595161d1a4a82007d288.

**Comment by rapidvelo** [comment]
Thank you @JaroslawWaliszko  and sorry for my confusion  I do not get the error however with empty string however when i surpress and hold the submit button I see the validation message, when I let go of the button the validation message disappears and the field is highlight in blue.   I was hoping with undefinied or empty string it would leave the validation message present?  Is there a way around this?

Thanks alot for your time.

**Comment by JaroslawWaliszko** [comment]
Hi. What do you mean by "surpress"? How do you do that? I'm asking because I'd like to reproduce that behavior. Please provide some details, either tiny code sample or screenshot. Regards.

**Comment by rapidvelo** [comment]
Just hold down the submit button (don’t let it go) and the client validation text will appear.  Once you let go of the submit button the client validation text disappears and only the field that’s not meeting the RequiredIf conditions is highlighted.    Where is you use the built in function of “Required” once you press the submit button and let go the client validation text – sticks and still appears.

Thanks for your time

**Comment by JaroslawWaliszko** [comment]
To be honest, I'm not able to notice that issue. I'm trying to reproduce it using the [sample project]( https://github.com/JaroslawWaliszko/ExpressiveAnnotations/tree/master/src/ExpressiveAnnotations.MvcWebSample) on Chrome and Firefox. Either I'm doing something not exactly how I'm supposed to, or I do not quite understand that case.
