### ISSUE TITLE
Client side enum type issue

### ISSUE THREAD

**Issue by rmmcgr** [JaroslawWaliszko/ExpressiveAnnotations#67]
I have a model that is used on a UI where it can be saved as a draft and only a few fields are validated. If the user "submits" it to the system validation on all fields is performed.

In order to do this I have been using a "ShouldValidate" bool field in the model and then setting this as appropriate when the user submits the form with jquery (this is an ASP.NET MVC 5 project).

One of the validation rules on the model is as follows:

```c#
[RequiredIf("ShouldValidate == true && Type == MyType.ValueA", ErrorMessage = "This field is required.")]
public string SomeField { get; set; }
```

The error on the client I get is:

```
Uncaught DOM field Type value conversion to numeric failed. Given value was not recognized as a valid float. jquery.validate.js:640
```
If I manually set the field that represents the enum type (which is called "Type") to an integer, it is fine.

How can I workout what is going on here?

**Comment by JaroslawWaliszko** [comment]
Hi, 
please provide also your c# code and the view (only the relevant parts). I'll try to reproduce that issue in the next week and provide an answer. Currently I have only phone with me. 
Regards.

**Comment by rmmcgr** [comment]
In putting together a test project, I also found out that it seems to be narrowed to the case where the enum is in a hidden field. If it is in a drop down, it is fine as the value if the enum is stored as a number where as for the hidden field it is a text string.

Here is my model class:
```c#
public class Test
    {
        public Test()
        {
            ShouldValidate = true;
            Status = TestStatus.Pending;
        }

        public int TestId { get; set; }
        public bool ShouldValidate { get; set; }
        public TestStatus Status { get; set; }

        [RequiredIf("ShouldValidate == true && Status == TestStatus.Pending", ErrorMessage = "Description is required")]
        public string Description { get; set; }
    }

    public enum TestStatus
    {
        Draft,
        Pending,
        Approved
    }
}
```
This is how I am calling the view in the controller (to setup the scenario where the error occurs):

```C#
public ActionResult Create()
{
    return View(new Test { Status = TestStatus.Pending, ShouldValidate = true });
}
```
Here is the view and how I am using it:

```HTML
@model ExpressiveAnnotationsTest.Models.Test

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Test</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(m => m.ShouldValidate)

        @Html.HiddenFor(m => m.Status)

        @*<div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

```
Finally, to trigger the error in the JavaScript console of my browser I can run:

```JavaScript
$("form").valid()
```

To get the error message back:
```
Uncaught DOM field Status value conversion to numeric failed. Given value was not recognized as a valid float. jquery.validate.js:640
```
Also of note in my view is the following JavaScript (which I have just to show what I am also have in my production system in case this is affecting anything):

```JavaScript
$(document).ready(function () {

            $.validator.methods.date = function (value, element) {
                // This is not ideal but Chrome passes dates through in ISO1901 (US) format regardless of locale
                // and despite displaying in the specified format.

                return this.optional(element)
                    || moment(value, "DD/MM/YYYY").isValid()
                    || moment(value, "YYYY-MM-DD").isValid();
            }

            $("form ").validate().settings.ignore = [];

        });
```

**Comment by JaroslawWaliszko** [comment]
Hi,

As you already noticed MVC provided `HiddenFor` helper does not provide convenient HTML to be used by EA - instead of `integer` value for `enum`, it renders its `string` equivalent. That's why EA is not able to use it for expression evaluation, because it needs a numeric value (which is e.g. properly given by `EnumDropDownListFor` helper).

The simplest workaround could be this line:
```
@Html.Hidden("Status", (int)Model.Status)
```

If you'd like to still use type aware helper, write one for your `enum` type. Under `Views->Shared->DisplayTemplates` path, add `TestStatusEnum.cshtml` file with the following content:
```
@model TestStatus
@Html.Hidden("", (int)Model)
```
The usage would be following:
```
@Html.DisplayFor(m => m.Status)
```
Do not forget to decorate `Status` field with appropriate attribute (which instructs MVC to use correct template for field rendering):
```
[UIHint("TestStatusEnum")]
public TestStatus Status { get; set; }
```

**Comment by rmmcgr** [comment]
As you suggested, we went with:
```C#
@Html.Hidden("Status", (int)Model.Status)
```
Thanks again for you help.

**Comment by Carlos-Liu** [comment]
I have met the same issue and I made it work as below

1. Add a property in the model class
```
public string TestStatusForAssert { get { return Status.ToString(); } }
```

2. Then change the assert condition by using the ```TestStatusForAssert``` string

```
 [RequiredIf("ShouldValidate == true && TestStatusForAssert== 'Pending'", ErrorMessage = "Description is required")]
        public string Description { get; set; }
```

The cons is that you need remember to change the string 'Pending' when the enum item is renamed
