### ISSUE TITLE
Client validation for AssertThat in EditorTemplate

### ISSUE THREAD

**Issue by speshulk926** [JaroslawWaliszko/ExpressiveAnnotations#72]
I can't seem to get my client validation running correctly in my editor template with an AssertThat. Right now, this page just does a full postback and displays a blank ValidationSummary. I'm not sure if it works with EditorTemplate since my names are 

    <input name="ClassName[0].PropertyName1" /> 

etc.  When I look at the rendered HTML, all I see is "PropertyName1 <= PropertyName2".  I'll show details below:

```c#
    public class ViewData 
    {
        public List<TakeOutOption> TakeOutOptions { get; set; }
        public decimal TotalAmountEligibleToTakeOut { get; set; }
    }

    public class TakeOutOption
    {
        public decimal CurrentValue { get; set; }
        [AssertThat("AmountToTakeOut <= CurrentValue", ErrorMessage = "Amount must not be more than the Current Value")]
        public decimal AmountToTakeOut { get; set; }
    }
```

Editor Template:

```html
    @model Models.TakeOutOptions 
    <tr>
        <td>@Model.CurrentValue.ToString("C")@Html.HiddenFor(x => x.CurrentValue)</td>
        <td>@Html.Bootstrap().TextBoxFor(m => m.AmountToTakeOut).Value(Model.AmountToTakeOut > 0 ? Model.AmountToTakeOut.ToString("N2") : "").HtmlAttributes(new { data_calculate_total = true }).Prepend("$")</td>
    </tr>
```

View: 

```html
    <table class="table">
        <thead>
            <tr>
                <th class="col-xs-2">Current Value</th>
                <th class="col-xs-3">Amount To Take Out</th>
            </tr>
        </thead>
        <tbody>
            @Html.EditorFor(x => x.TakeOutOptions)
        </tbody>
        <tfoot>
            <tr>
                <td>@Model.TotalAmountEligibleToTakeOut.ToString("C")</td>
                <td class="text-right">
                     @Html.Bootstrap().TextBoxFor(m => m.TotalAmountEligibleToTakeOut).Readonly().Prepend("$").Class("remove-disable-look")
                 </td>
             </tr>
         </tfoot>
     </table>
```

The HTML Output ( I only pasted in the part where the validations are set ) :

```html
    <tr>
        <td>
            $45.00<input name="TakeOutOptions[0].CurrentValue" id="TakeOutOptions_0__CurrentValue" type="hidden" value="45" data-val-required="The CurrentValue field is required." data-val="true" data-val-number="The field CurrentValue must be a number.">
        </td>
        <td>
            <div class="input-group">
                <span class="input-group-addon">$</span>
                <input name="TakeOutOptions[0].AmountToTakeOut" class="form-control" id="TakeOutOptions_0__AmountToTakeOut" type="text" value="" data-val-required="The AmountToTakeOut field is required." data-val="true" data-val-number="The field AmountToTakeOut must be a number." data-val-assertthat-fieldsmap='{"AmountToTakeOut":"numeric","CurrentValue":"numeric"}' data-val-assertthat-expression="AmountToTakeOut <= CurrentValue" data-val-assertthat-constsmap="{}" data-val-assertthat="Amount must not be more than the Current Value" data-calculate-total="True">
            </div>
        </td>
    </tr>

    <tr>
        <td>
            $55.00<input name="TakeOutOptions[1].CurrentValue" id="TakeOutOptions_1__CurrentValue" type="hidden" value="55" data-val-required="The CurrentValue field is required." data-val="true" data-val-number="The field CurrentValue must be a number.">
        </td>
        <td>
            <div class="input-group"><span class="input-group-addon">$</span>
                <input name="TakeOutOptions[1].AmountToTakeOut" class="form-control" id="TakeOutOptions_1__AmountToTakeOut" type="text" value="" data-val-required="The AmountToTakeOut field is required." data-val="true" data-val-number="The field AmountToTakeOut must be a number." data-calculate-total="True" data-val-assertthata-fieldsmap='{"AmountToTakeOut":"numeric","CurrentValue":"numeric"}' data-val-assertthata-expression="AmountToTakeOut <= CurrentValue" data-val-assertthata-constsmap="{}" data-val-assertthata="Amount must not be more than the Current Value">
            </div>
        </td>
    </tr>
```

Is there a better way to do this to add validation to AssertThat the amount typed in is <= the amount allowed?

**Comment by JaroslawWaliszko** [comment]
Hi. To be honest I don't know the answer right now. It can be an enhancement request (or bug) as well. This issue needs some investigation.

**Comment by speshulk926** [comment]
This was driving me crazy, so I moved it into its own project and removed all of my addons except Expressive Annotations and it seems to work as intended.  I type in an amount > my CurrentValue and I got the client side validation.  I'm guessing it's something else on my page that is not working.  Having said that though, the error messages are all generic so I am having to over-ride the erorr message property in the Editor Template otherwise, if there are 8 rows and you type in an invalid amount in all 8 rows, you get 8 of the same errors in the summary.

Thanks for looking.

**Comment by JaroslawWaliszko** [comment]
Good to hear that. 

I'd like to add that, if something is still not working as expected in some areas, you can always prepare sample project where such an issue can be reproduced (that project should compile and be as simple as possible), and attach it to this discussion. It would be easier to have it here.

Regards

**Comment by JaroslawWaliszko** [comment]
In the next version (2.6.0), client script is going to have `ea.settings.debug` option (turned off by default). If activated, some messages will be displayed to the web console, about what expressions are going to execute right now, in which context, for which fields, also what dependency triggers are fired if any, and finally some warnings if detected. Maybe it will be helpful in such a cases.

**Comment by speshulk926** [comment]
This is great news.  Thanks!
