### ISSUE TITLE
Tab Control

### ISSUE THREAD

**Issue by PTWSys** [JaroslawWaliszko/ExpressiveAnnotations#74]
I hope I've posted this question in the correct place...
I’ve managed to implement your solution and it works a treat. Even got your progress bar displaying in my WPF application.
I’m just stuck on how to display an error alert icon in the header of a tab item control to indicate on which tab the error occurred?
Any help on this would be appreciated.
Thanks

**Comment by JaroslawWaliszko** [comment]
Unfortunately this question is too broad, related to WPF programming, no to EA itself. It does not fit in the scope here.
