### ISSUE TITLE
Move ValueParserAttribute to ExpressiveAnnotations

### ISSUE THREAD

**Issue by girtsl** [JaroslawWaliszko/ExpressiveAnnotations#77]
Hi,

Currently the ValueParser attribute can only be applied to models that reside in projects referencing ExpressiveAnnotations.MvcUnobtrusive even though there is nothing MVC-specific in the class.
This prevents devs that keep models in separate projects (e.g. to share between different apps) and only reference ExpressiveAnnotations from using the attribute (and thus using custom parsers).

Please consider moving the attribute to ExpressiveAnnotations project, similar to all the other attributes.

**Comment by JaroslawWaliszko** [comment]
Hi,

My thinking is `ValueParser` attribute is just a marker. It provides a hint for client-side script, pointing at specific parser, which should be used for DOM field value deserialization. 

I agree that there is nothing MVC-specific in that class, but only when combined with MVC validators (`ExpressiveValidator` inherited from `DataAnnotationsModelValidator` to be specific, which next feeds expressive.annotations.validate.js) it means something. It does nothing by itself, so at server-side only I see no purpose for its existence. 

You do not need do include the scripts and MVC assembly when ExpressiveAnnotations.MvcUnobtrusive.dll is referenced (remove manually all unused references after NuGet installation is done).

![image](https://cloud.githubusercontent.com/assets/1596462/9790092/6859b12e-57d4-11e5-8a79-d5dd91af7872.png)

I see no issues here or I do not fully understand this problem. I'm opened for a discussion anyway.

Regards

**Comment by girtsl** [comment]
I figured as much :) Perhaps describing my use case will illustrate my point better. 
I have a MVC application that would actually make use of the attribute. However, the model class, whose properties are decorated with the attribute, resides in a separate project (just like in your image) that only has reference to `ExpressiveAnnotations` (and I would like to keep it that way). The reason the model is in a separate project is that it's also used by a WebAPI project.
Moving the attribute to `ExpressiveAnnotations` would decrement the dependency count by one and not require some stuff to be manually removed - less friction for the developers. I would image one would have to remove the extra stuff every time the NuGet package is updated.

**Comment by JaroslawWaliszko** [comment]
It's like a trade-off I need to think about change because I'm not convinced. This particular attribute doesn't fit to ExpressiveAnnotations.dll functionally, and to me it would be a redundant element there (e.g. for someone who uses server-side only models in WPF applications). In other cases like yours though, where client-side is used, but domain model is separated, additional dependency ExpressiveAnnotations.Mvcunobtrusive.dll is required to be referenced because of that attribute usage.

**Comment by girtsl** [comment]
You are right, it is a trade-off. On one hand you would have a class sitting in a project it doesn't really belong to, but on the other, there is extra stuff to be removed every time the NuGet package is installed or updated.
Even though the second case doesn't affect all users, imho it's worth avoiding the extra friction of removing stuff manually.

**Comment by JaroslawWaliszko** [comment]
Ok. It's done here: https://github.com/JaroslawWaliszko/ExpressiveAnnotations/commit/a665acc2c0f185e940f3272cfced7a8e25f9c13a.

**Comment by girtsl** [comment]
Great! Thank you!
