### ISSUE TITLE
At least one required

### ISSUE THREAD

**Issue by gdycus** [JaroslawWaliszko/ExpressiveAnnotations#78]
Can you please help. I've got 4 nullable properties and I want to make sure at least one of them has a value. I've tried several different configurations with no luck. The ExpressiveAnnotation can be on the Adults property. Thanks!

public short? Adults { get; set; }
public short? Children { get; set; }
public short? AdultsNoInventory { get; set; }
public short? ChildrenNoInventory { get; set; }

**Comment by JaroslawWaliszko** [comment]
Try this:

```
[RequiredIf("Children == null && AdultsNoInventory == null && ChildrenNoInventory == null")]
public short? Adults { get; set; }

[RequiredIf("Adults == null && AdultsNoInventory == null && ChildrenNoInventory == null")]
public short? Children { get; set; }

[RequiredIf("Adults == null && Children == null && ChildrenNoInventory == null")]
public short? AdultsNoInventory { get; set; }

[RequiredIf("Adults == null && Children == null && AdultsNoInventory == null")]
public short? ChildrenNoInventory { get; set; }
```

**Comment by gdycus** [comment]
I recall having this problem before, but “== null” on a nullable property doesn’t seem to work with expressive annotations. The model state is valid when all 4 input are empty.

On Sep 18, 2015, at 1:48 PM, Jaroslaw Waliszko <notifications@github.com<mailto:notifications@github.com>> wrote:


Try this:

[RequiredIf("Children == null && AdultsNoInventory == null && ChildrenNoInventory == null")]
public short? Adults { get; set; }

[RequiredIf("Adults == null && AdultsNoInventory == null && ChildrenNoInventory == null")]
public short? Children { get; set; }

[RequiredIf("Adults == null && Children == null && ChildrenNoInventory == null")]
public short? AdultsNoInventory { get; set; }

[RequiredIf("Adults == null && Children == null && AdultsNoInventory == null")]
public short? ChildrenNoInventory { get; set; }

**Comment by gdycus** [comment]
This simple example doesn't seem to work either. If DiscountTypeKey = 4 and ClientLocationDiscountKey is NULL, the model state is still valid. Appears to be an issue with a nullable property.

[ExpressiveAnnotations.Attributes.RequiredIf("DiscountTypeKey == 4", ErrorMessage = "You must select a discount")]
public long? ClientLocationDiscountKey { get; set; }

public short DiscountTypeKey { get; set; }

**Comment by JaroslawWaliszko** [comment]
It's tested for `nullable` types (you can take a look at the unit tests). Examples are indeed simple and clearly work as expected - both client- and server-sides: 
---
![image](https://cloud.githubusercontent.com/assets/1596462/9970341/dd4894d8-5e54-11e5-9e18-b55ceb2d69cd.png)

---
![image](https://cloud.githubusercontent.com/assets/1596462/9970353/f42ffdf8-5e54-11e5-861a-f8c5c4a4f06f.png)

I'm afraid I don't know what your error is since you've not provided any log from the web console nor server exceptions etc. I assume your configuration is broken.
