### ISSUE TITLE
I18N

### ISSUE THREAD

**Issue by ivanof77** [JaroslawWaliszko/ExpressiveAnnotations#84]
Hi, 
do you think that's possible using resource file for create an error message?
Something like this:
[RequiredIf("email == null", ErrorMessageResourceName = "emailValidationError", ErrorMessageResourceType = typeof(MyResources.Resources))]
Can you help me?
Regards,
ER.

**Comment by JaroslawWaliszko** [comment]
Yes it is a standard behaviour. Where is the problem?

**Comment by ivanof77** [comment]
Sorry Jaroslaw, 
is my mistake!
Regards,
ER.
