### ISSUE TITLE
Is it possible to use ExpressiveAnnotations with .Net 3.0 and how?

### ISSUE THREAD

**Issue by hyperion1** [JaroslawWaliszko/ExpressiveAnnotations#87]

**Comment by JaroslawWaliszko** [comment]
The compatibility is granted from NET 4.0. NET 3.0 is not supported. 

*System.ComponentModel.DataAnnotations* namespace has been added to the framework in 3.5 SP1. There was also no LINQ at that time (while I'm using it extensively e.g. in the parser implementation).
